### ISSUE TITLE
'Select A' instead of the option name

### ISSUE THREAD

**Issue by connecticus** [fidenz-suchith/spree_variant_options#1]
instead of the option name, such as size, color, etc., is displayed 'Select A'

**Comment by fidenz-suchith** [comment]
Hi Connecticus

This seems to be working fine. Is it possible for you to attach a screenshot of what you are getting?

Thanks.

**Comment by connecticus** [comment]
Hi, fidenz-suchith, 

Thank you very much for your reply,
now I decided to check  localization settings. It seems the problem was in it.

Another question: The description says that the key converted to the selectors. But I have not.

![screenshot_2015_03_04_22_30_40](https://cloud.githubusercontent.com/assets/1949072/6500307/e04f0cf2-c2be-11e4-88bf-94439fea15f9.png)

**Comment by fidenz-suchith** [comment]
Hi,

Its actually a ul tag styled as a selector and once you click on it, it should work as a selector. Is it listing all the values under an option one by one?

**Comment by connecticus** [comment]
I understood you, thank you!

**Comment by connecticus** [comment]
I try to combine spree_variant_options and spree_variant_properties. To get variant properties for each variant I use ' <li><%= link_to value.has_image? ? image_tag(value.image.url, :alt => value.presentation) : content_tag(:span, value.presentation), "#",:value => value.presentation, :id => lindex.to_s+xindex.to_s, :title => value.presentation, :class => classes.join(" "), :rel => "#{type.id}-#{value.id}", onclick: "Spree.updateVariantProperties('#{@product.slug}', #{@variant.id});" %></li>'

But, I cant get a variant.id. Error: undefined method `id' for nil:NilClass

Have you tried to do something like that? Just such a combination of plug-ins would be very useful.

Thank you!

**Comment by fidenz-suchith** [comment]
Hi,

No I haven't tried it yet. But if you can clearly explain what you want to, It would be a great extension that I could write in leisure time! :)

**Comment by connecticus** [comment]
Yes, it might be useful thing.  Very often variants have different properties. And on click on selected variant, property name and value must change. Solution for this is  spree_variant_properties gem.

In normal case to activate spree_variant_properties I just add onclick event in _cart_form.html.erb. For ex:

```
          <%= radio_button_tag "variant_id", variant.id, index == 0, 'data-price' => variant.price_in(current_currency).money, onclick: "Spree.updateVariantProperties('#{@product.slug}', #{variant.id});"  %>
```

so we update the output table properties, depending on the variant (on click)

So that works spree_variant_properties - https://github.com/connecticus/spree_variant_properties

The difficulty is that I try to combine spree_variant_options and spree_variant_properties now. 

Main problem is that: I can't get variant.id if I add onclick event in 

```
        <li><%= link_to value.has_image? ? image_tag(value.image.url, :alt => value.presentation) : content_tag(:span, value.presentation), "#",:value => value.presentation, :id => lindex.to_s+xindex.to_s, :title => value.presentation, :class => classes.join(" "), :rel => "#{type.id}-#{value.id}", onclick: "Spree.updateVariantProperties('#{@product.slug}', #{@variant.id});" %></li>
```

![screenshot_2015_03_06_02_44_51](https://cloud.githubusercontent.com/assets/1949072/6524094/e053a496-c3aa-11e4-9e04-6b3ef967d8c5.png)

Thus the need to substitute the current variant.id to the specified location. 

Then on click variants buttons, we can get updates in propetrties table :)
